schemaVersion: 2

publisher:
  author: "developer@example.com"
  company: "Example Corp"

publish:
  tlsKey: "aos-user-sp.p12"
  domain: "aoscloud.io"

items:
  - identity:
      type: "service"
      codename: "hello-aos"
      title: "Hello AOS Service"
      description: "Simple hello world C++ service"
    version: "1.0.0"
    sourceFolder: "service"

    images:
      - sourceFolder: "src_amd64"
        archInfo:
          architecture: "amd64"
        workingDir: "/"
        cmd: "/hello-aos"
      - sourceFolder: "src_arm64"
        archInfo:
          architecture: "arm64"
        workingDir: "/"
        cmd: "/hello-aos"

    configuration:
      workingDir: "/"
      cmd: "/hello-aos"
      instances:
        minInstances: 1
        priority: 10
      quotas:
        cpuLimit: 1000
        ramLimit: 10MB
        storageLimit: 5MB
        stateLimit: 512KB
        tmpLimit: 256MiB
